platform:
    resource: "@PlatformBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
     resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
     options:
           expose: true